baseURL = '/'
languageCode = 'en-gb'
title = "Connor's Cuisine"
theme = 'ananke'

[taxonomies]
  tags = "tags"
  categories = "categories"
  rating = "rating"
  review = "review"
  difficulty = "difficulty"
  ingredients = "ingredients"